:scrollbar:
:noaudio:
:imagesdir: images
:toc2:
:linkattrs:
:data-uri:

== Assignment Lab

.Goal
* Assess hands-on proficiency with Advanced Development with Red Hat 3scale API Management topics

.Expectations
* Assignments take approximately 6 to 8 hours to complete.
* Assignments are an individual effort--you must complete the assignment without collaboration.
* Assignments simulate a challenge typically encountered in a Red Hat consulting engagement.
** Assignment requirements are intentionally vague.

.Grading
* Minimum *75%* score needed to pass

.Criteria
* 25%: API Service Setup section
* 25%: Methods, Metrics, Rate Limits Setup section
* 25%: User Signup Setup section
* 25%: Development Portal and API Docs section


.Deliverables
* Provide a README file with the following:
** Your Admin Portal and Developer Portal environments (host, admin user/password, developer signup link)
** Sufficient documentation for each section explaining your design choices
*** Sections without documentation will not be graded

.Environment
* You may choose where to deploy your solution.
** If you recently completed the _Red Hat 3scale API Management Implementation_ course or _Red Hat 3scale API Management Development_ course, you may use the same environment for this assignment.
** You can set up your own environment, but it must be accessible by the instructor.


:numbered:

== Business Use Case

You are a consultant assigned to WebRetail Inc., an e-commerce hosting platform. 
They are developing a new online retail platform branded "CoolStore" through which their partners can provide a catalog and inventory to sell products through the platform.

WebRetail Inc. is adopting a new microservices architecture and wants to make its retail platform APIs available as REST APIs. 
It has asked you to lead a proof-of-concept (POC) using Red Hat 3scale API Management. 
The purpose of the POC is to determine the feasibility of using 3scale API Management for managing WebRetail's APIs, providing a standard portal for its partners to access the APIs, setting up partner tier-based plans, providing standard API documentation, and automating signup for the developers.

== Business Services

WebRetail Inc. has made its CoolStore microservices project available to you:

* link:https://github.com/gpe-mw-training/3scale_development_labs/tree/master/CoolStore[Inventory and Catalog service source code]

=== Provision Business Services

You need to deploy the catalog and inventory services in your OpenShift project to enable these to be accessed by your 3scale API Management environment.

==== Provision Catalog Service

. Open a terminal window and log in to your OpenShift Container Platform web console.

. Create a new project for your products API business service applications:
+
[source,sh]
-----
$ oc new-project $OCP_USERNAME-coolstore \
     --display-name="CoolStore API" \
     --description="CoolStore API Business Services"
-----

. Create a ConfigMap for the catalog service:
+
[source,sh]
-----
$ mkdir -p $HOME/lab



$ echo "
catalog.http.port: 8080
connection_string: mongodb://catalog-mongodb:27017
db_name: catalogdb
username: mongo
password: mongo" > $HOME/lab/app-config.yaml




$ oc create configmap app-config --from-file=$HOME/lab/app-config.yaml -n $OCP_USERNAME-coolstore
-----


. Allow the default system administrator to read the ConfigMap deployed in the namespace:
+
[source,sh]
-----
$ oc policy add-role-to-user view -z default -n $OCP_USERNAME-coolstore
-----

. Import the `catalog` template into your OpenShift environment:
+
[source,sh]
-----
$ oc create -f https://raw.githubusercontent.com/gpe-mw-training/3scale_development_labs/master/CoolStore/coolstore-catalog-mongodb-persistent.yaml -n $OCP_USERNAME-coolstore
-----

. Create a new application using the `coolstore` template:
+
[source,sh]
-----
$ oc new-app \
        --template=coolstore-catalog-mongodb \
        -p CATALOG_DB_USERNAME=mongo \
        -p CATALOG_DB_PASSWORD=mongo \
        -n $OCP_USERNAME-coolstore
-----


. Wait about one minute for the MongoDB database to start and then resume the `catalog-service` from its paused state:
+
[source,sh]
-----
$ oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
catalog-mongodb-1-zlsjx   1/1       Running   0          50s

$  oc rollout resume deploy/catalog-service -n $OCP_USERNAME-coolstore
-----

. Smoke test the catalog service APIs:
.. Test the OAS documentation:
+
[source,texinfo]
-----
$ curl -k http://`oc get route -n $OCP_USERNAME-coolstore  catalog-unsecured --template {{.spec.host}}`/docs/coolstore-catalog-microservice-swagger.yaml
-----

.. Test the products resources:
+
[source,texinfo]
-----
$ curl -k http://`oc get route -n $OCP_USERNAME-coolstore  catalog-unsecured --template {{.spec.host}}`/products
-----


==== Provision Inventory Service

. (Optional) Review the inventory service source code link:https://github.com/gpe-mw-training/cnd_thorntail_experienced/tree/api-mgmt-inventory-service[here].

. Create a ConfigMap for the inventory service:
+
[source,sh]
-----
$ echo "
swarm:
  datasources:
    data-sources:
      InventoryDS:
        driver-name: postgresql
        connection-url: jdbc:postgresql://inventory-postgresql:5432/inventorydb
        user-name: jboss
        password: jboss"  >  $HOME/lab/inventory-config.yaml


$ oc create configmap inventory-config --from-file=$HOME/lab/inventory-config.yaml -n $OCP_USERNAME-coolstore
-----

. Import the `inventory` template into your OpenShift environment:
+
[source,sh]
-----
$ oc create -f https://raw.githubusercontent.com/gpe-mw-training/3scale_development_labs/master/CoolStore/coolstore-inventory-persistent.yaml -n $OCP_USERNAME-coolstore
-----

. Create a new `inventory` application:
+
[source,sh]
-----
$ oc new-app \
    --template=coolstore-inventory-postgresql \
    -p INVENTORY_SERVICE_NAME=inventory-service \
    -p INVENTORY_DB_USERNAME=jboss \
    -p INVENTORY_DB_PASSWORD=jboss \
    -p INVENTORY_DB_NAME=inventorydb
-----


. Wait about one minute for the PostgreSQL database to start and then resume the `inventory-service` from its paused state:
+
[source,sh]
-----
$ oc get pods

.....

inventory-postgresql-1-rn96s           1/1       Running            0         50s




$ oc rollout resume deploy/inventory-service -n $OCP_USERNAME-coolstore
-----

. Smoke test the inventory service APIs:
.. Test the OAS documentation:
+
[source,texinfo]
-----
$ curl -k -X GET http://`oc get route -n $OCP_USERNAME-coolstore  inventory-unsecured --template {{.spec.host}}`/swagger.json | python -m json.tool
-----

.. Test the inventory resource:
+
[source,texinfo]
-----
$ curl -k -X GET http://`oc get route -n $OCP_USERNAME-coolstore  inventory-unsecured --template {{.spec.host}}`/inventory/165613 | python -m json.tool
-----

The following are the valid product IDs seeded for this POC, which you can use to try sample requests for the catalog and inventory APIs:

* `329299`
* `329199`
* `165613`
* `165954`
* `444434`
* `444435`
* `444436`



=== Explore APIs

Recall from the previous section that OpenAPI documentation is provided for both APIs.

You can use the link:http://editor.swagger.io/[Swagger editor] to explore the available methods and mappings that you can set up for the APIs in 3scale API Management.


== POC Requirements

WebRetail Inc. management requires that you include all of the items listed in these subsections in your POC.

=== 3scale API Services

* The inventory and catalog services must be managed separately.
* Each service must have a basic plan and a premium plan so that WebRetail Inc. can provide differentiated plans to users.
* The basic plan must not have the ability to invoke Create, Update, or Delete operations on the services. It must be allowed READ access only.
** The premium plan must not impose any restrictions.
** The basic plan users must be limited to 5 API requests per hour for each service.
* Metrics must be set up so that usage details can be viewed for each method separately.

=== Developer Portal and User Experience

* Developers must be able to access a publicly hosted Developer Portal to access their application plans and API documentation.
* The Developer Portal must be branded with the CoolStore logo and APIs.
* The inventory and catalog services must be the only services that users can sign up to.
* Developers must be able to choose their plans for each service and sign up simultaneously to both services.
* If a developer chooses the basic plan, the plan must be approved automatically.
* If a developer chooses the premium plan, the plan must be approved first by an administrator before they can access the APIs.
* API docs must be available through the Developer Portal for developers to test the APIs.

=== API Gateway

* The API gateway must be colocated with the backend business services in the same OpenShift cluster to reduce latency.
* The API gateway must expose separate HTTPS based routes for each service.
* Once the API services are exposed on the APIcast gateway, the API back-end routes must not have a publicly available URL that can be accessed directly.

== Homework Submittal

* You submit your homework via one of the following:

** *Red Hat employees*: link:https://docs.google.com/document/d/1nxlvAOlSdNs3-y8AkmDjnc8vtCH9rJdI5zbN9deCK50/edit[Red Hat LMS]
** *Red Hat partners*: link:https://partner.redhat.com[Red Hat Connect]

* To submit the assignment for grading, upload a README file with the following information:

** 3scale Admin Portal URL, admin userid/password
** 3scale Developer Portal URL and signup page
** Sample `curl` requests for each service at the production endpoint
** Information about any design considerations for each section describing your choices
** Any additional points or information relating to the assignment that you want to share
** Any time limits, such as an environment expiry date after which the solution is inaccessible for testing
+
NOTE: Make sure that the lab environment is accessible for up to one week after submission, to enable the instructor to access the URLs for grading.
