:scrollbar:
:data-uri:
:toc2:
:linkattrs:


== Lab Setup

.Goals

* Review of lab assets
* Orientation to multitenant API Manager lab environment
* Provision APIcast gateways

.Prerequisites
* Completion of the following courses:
** link:https://learning.redhat.com/course/view.php?id=739[App Development using RHT OpenShift Container Platform]
** link:https://learning.redhat.com/course/view.php?id=977[RHT 3scale Implementation]
** link:https://learning.redhat.com/course/view.php?id=1121[RHT 3scale Development]

:numbered:

== Client tooling

To execute the labs in this course, you will need some client tooling.
This includes the OpenShift command line utility (`oc`) as well as the course lab asseets.

You can continue to  utilize the same link:https://drive.google.com/file/d/1Ee5h0_YpWcJ0Lt3boBXujsCghcarABFF/view?usp=sharing[client virtual machine] that you used in the API mgmt related pre-requisite courses.

In the client virtual machine, ensure you are using the `jboss` operating system user.

Recall that the lab assets for this course are version controlled at:  `https://github.com/gpe-mw-training/3scale_development_labs.git`
If you are not using the course client VM, then please clone this repository to the following directory:  $HOME/lab/33scale_development_labs .

Refresh these lab assets by navigating to $HOME/lab/3scale_development_labs and executing:

-----

$  git pull origin master
-----

== Environment Variables

Open a terminal window and set the following environment variables that will be used throughout the duration of this course.

ifdef::showscript[]
If student lab environment and 3scale tenants were provisioned using the ocp-workload-rhte-mw-api-mesh ansible role, then student details can be found in:

$HOME/provisioning_output/$OCP_WILDCARD_DOMAIN/$TENANT_HAME/$ocp_amp_admin_username_tenant_info_file_$START_TENANT_$END_TENANT.txt
endif::showscript[]

-----
# Modify each of the following based on settings provided by Instructor
# Afterwards, exeecute each of the modified commands in your shell:

$ echo "export REGION=<provided by your instructor>" >> ~/.bashrc
$ echo "export OCP_USERNAME=<provided by your instructor>" >> ~/.bashrc
$ echo 'export OCP_PASSWD=<provided by your instructor>' >> ~/.bashrc
$ echo "export API_ADMIN_ACCESS_TOKEN=<provided by your instructor>" >> ~/.bashrc



#  Review, copy & paste the following in same terminal #

echo "export OCP_WILDCARD_DOMAIN=apps.\$REGION.openshift.opentlc.com" >> ~/.bashrc
echo "export TENANT_NAME=3scale-mt-amp0" >> ~/.bashrc
echo "export GW_PROJECT=\$OCP_USERNAME-gw" >> ~/.bashrc
echo "export THREESCALE_PORTAL_ENDPOINT=https://\$API_ADMIN_ACCESS_TOKEN@\$OCP_USERNAME-\$TENANT_NAME-admin.\$OCP_WILDCARD_DOMAIN" >> ~/.bashrc



# Execute the following to enable the variables in your existing shell
source ~/.bashrc
-----


== Red Hat OpenShift Container Platform

. Using both your browser as well as the `oc` utility in the client vm, authenticate into your OCP environment.
+
The URL of the master node will be the output of the following:
+
-----
$  echo -en "\n\nhttps://master.$REGION.openshift.opentlc.com\n\n"
-----
+
At the login prompt (of both the oc utility and your browser), use the values of `$OCP_USERNAME` and `$OCP_PASSWD`

. Once you have authenticated in, you should see two OpenShift projects :
+
-----
$ oc get projects

...

3scale-mt-amp0   3scale-mt-amp0   Active
user1-gw                          Active
-----

.. *3scale-mt-amp0*
+
Your OCP user has been provided with _view_ access to the central multi-tenant API Manager.

.. *$OCP_USERNMAE-gw*
+
This namespace includes an API gateway pre-configured to interact with your API Management tenant.


== Multitenant 3scale API Manager

Your lab environment includes access to a multi-tenant 3scale API Manager installation.

For the purpose of this lab, you will serve as the administrator of your own 3scale _tenant_ (aka: _domain_)

. To access the admin portal of your 3scale environment, point to your browser to the output of the following:
+
-----
$ echo -en "\n\nhttps://$OCP_USERNAME-$TENANT_NAME-admin.$OCP_WILDCARD_DOMAIN\n\n"
-----

. Authenticate using the values of $OCP_USERNAME and $OCP_PASSWD
+
Your 3scale credentials are the same as your OCP credentials.


== API Gateways

=== API Manager Gateways

Your 3scale API Manager multitenant lab environment does come with a set of associated staging and production apicast gateways.

These gateways can be seen by executing the following:

-----
$ oc get dc -n $TENANT_NAME | grep apicast


apicast-production        1          1         1         config,image(amp-apicast:latest)
apicast-staging           1          1         1         config,image(amp-apicast:latest)
apicast-wildcard-router   1          1         1         config,image(amp-wildcard-router:latest)-
-----

It is technically feasible that your backend services, if they were to be  co-located in the same cluster as the API Manager, could be managed by these default API Manager gateways.

One practical hinderance however is that these gateways are owned by the 3scale master user and the OCP cluster-admin.
You, as a non cluster-admin,  do not have the ability to bounce these gateways, nor modify them if need be.

It also would be difficult to identify your logs while everyone's traffic flows through those gateways at the same time.

These default API Manager gateways are of minimal value to you.

=== Tenant specific API Gateways

Your lab environment comes pre-provisioned with a set of API gateways that are specific to your tenant.
You have full administrative access to your tenant specific API gateways.
These are the API gateways that you will use to manage your backend services for the duration of this course.

. You can get a list of these API gateways by executing the following:
+
-----
$ $ oc get deploy -n $GW_PROJECT


NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
prod-apicast    1         0         0            0           7h
stage-apicast   1         0         0            0           7h
-----

. Notice the value of _$THREESCALE_PORTAL_ENDPOINT_ has already been set for you in each of your gateways:
+
-----
$ oc describe deploy prod-apicast -n $OCP_USERNAME-gw | grep THREESCALE_PORTAL_ENDPOINT

      THREESCALE_PORTAL_ENDPOINT:    https://b753490aa7586f8e0663f5d5ec62b63cf9e71540d9138e4869eede4446e8e871@user1-3scale-mt-amp0-admin.apps.3295.openshift.opentlc.com
-----
+
The API Gateway uses the value of _THREESCALE_PORTAL_ENDPOINT_ invoke the API Manager and retrieve details of your APIs.

. Resume the paused deploy objects:
+
-----
$ oc rollout resume deploy stage-apicast prod-apicast -n $GW_PROJECT
-----

== Smoke Test

In this section of the lab, you smoke test the management of any RESTful service of your choice using your 3scale API Manager and API gateways.

As backend services, you can use the same ones used in the pre-req courses (ie:  helloworld _swarm_ or _vertx_ based services) .
Another option is to conduct a smoke test using the _Echo API_ pre-configured with a new API tenant..

ifdef::showscript[]
endif::showscript[]
